name: "Labeler"


on:
  pull_request_target:

jobs:
  labeler:
    name: Labeler
    runs-on: ubuntu-22.04
    steps:
      - uses: tibdex/github-app-token@v2
        id: generate_token
        with:
          app_id: ${{ secrets.BOT_APPLICATION_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}

      - uses: fuxingloh/multi-labeler@v4
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          config-path: .github/labeler.yml
