# Build changed apps and push it to ECR

name: Build and push

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    if: "!contains(toJSON(github.event.commits.*.message), 'chore(release):')"
    runs-on: ubuntu-22.04
    name: Build and publish
    steps:
      - uses: tibdex/github-app-token@v2
        id: generate_token
        with:
          app_id: ${{ secrets.BOT_APPLICATION_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}

      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          token: ${{ steps.generate_token.outputs.token }}
          fetch-depth: '0'

      - name: Enable Corepack and Configure Yarn
        run: |
          corepack enable
          corepack install --global yarn@4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'

      - name: Fetch git tag refs
        run: git fetch --all --tags

      - name: Publish
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          yarn install --immutable
          yarn run build:all
          yarn lerna publish --no-private --yes
