name: Run tests

on:
  pull_request:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    runs-on: ubuntu-22.04
    name: Test
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: "0"

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: 'yarn'
          
      - name: Enable Corepack and Configure Yarn
        run: |
          corepack enable
          corepack install --global yarn@4

      - name: Install node modules
        run: |
          yarn install

      - name: Test
        run: |
          yarn run test:all
